name: Continuous Integration

# This action works with pull requests and pushes
on:
  pull_request:
  push:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout on push
        # github object: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
        # event names: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
        if: "github.event_name == 'push'"
        uses: actions/checkout@v2

      - name: Prettify code
        uses: creyD/prettier_action@v3.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,md}
       - name: Autoformat
         id: format
         uses: Luohaothu/auto-format@master